/**
 * WebClipper template types and interfaces.
 *
 * These types match the Obsidian Web Clipper JSON schema (v0.1.0).
 * Used for bidirectional conversion between WebClipper JSON and Templater MD formats.
 *
 * @module clipper/types
 */

/**
 * Property types supported by WebClipper.
 * - text: Single-line text field
 * - date: Date field (YYYY-MM-DD format)
 * - multitext: Multi-value text field (tags, links)
 * - number: Numeric field
 * - checkbox: Boolean field
 */
export type WebClipperPropertyType =
	| "text"
	| "date"
	| "multitext"
	| "number"
	| "checkbox";

/**
 * A single property in a WebClipper template.
 * Properties become frontmatter fields in the generated note.
 */
export interface WebClipperProperty {
	/** Property ID (auto-generated by WebClipper, optional) */
	id?: string;
	/** Property name (becomes frontmatter field name) */
	name: string;
	/** Property value (may contain template variables like {{url}}) */
	value: string;
	/** Property type for Obsidian */
	type: WebClipperPropertyType;
}

/**
 * WebClipper template behavior.
 * - create: Creates a new note
 * - append: Appends to an existing note
 */
export type WebClipperBehavior = "create" | "append";

/**
 * A WebClipper template definition.
 * This is the JSON format exported from Obsidian Web Clipper.
 */
export interface WebClipperTemplate {
	/** Schema version (currently "0.1.0") */
	schemaVersion: string;
	/** Template name (displayed in WebClipper UI) */
	name: string;
	/** Behavior when clipping (create new or append to existing) */
	behavior: WebClipperBehavior;
	/** Note filename format with template variables */
	noteNameFormat: string;
	/** Target folder path in vault */
	path: string;
	/** Content context for AI prompts (CSS selector or schema.org data) */
	context?: string;
	/** Note body content format with template variables */
	noteContentFormat: string;
	/** Frontmatter properties */
	properties: WebClipperProperty[];
	/** URL triggers for auto-selecting this template */
	triggers?: string[];
}

/**
 * WebClipper settings export format.
 * This is the full settings.json exported from the extension.
 */
export interface WebClipperSettings {
	/** Configured vaults */
	vaults?: WebClipperVault[];
	/** All templates (embedded in settings) */
	templates: WebClipperTemplate[];
	/** Property type definitions */
	propertyTypes?: WebClipperPropertyTypeDefinition[];
	/** General settings */
	generalSettings?: Record<string, unknown>;
}

/**
 * Vault configuration in WebClipper settings.
 */
export interface WebClipperVault {
	/** Vault name */
	name: string;
	/** Whether this is the active vault */
	isActive?: boolean;
}

/**
 * Property type definition for custom property types.
 */
export interface WebClipperPropertyTypeDefinition {
	/** Property name pattern */
	name: string;
	/** Property type */
	type: WebClipperPropertyType;
}

/**
 * Result of parsing a WebClipper template.
 */
export interface ParseResult<T> {
	/** Whether parsing succeeded */
	success: boolean;
	/** Parsed data (if successful) */
	data?: T;
	/** Error message (if failed) */
	error?: string;
	/** Validation warnings (non-fatal issues) */
	warnings?: string[];
}

/**
 * Templater variable in a template.
 * Used when converting WebClipper variables to Templater format.
 */
export interface TemplaterVariable {
	/** Variable name (e.g., "title", "url") */
	name: string;
	/** Default value (if any) */
	defaultValue?: string;
	/** Whether this is a date variable */
	isDate?: boolean;
	/** Date format (e.g., "YYYY-MM-DD") */
	dateFormat?: string;
	/** Prompt label for user input */
	promptLabel?: string;
}

/**
 * Conversion result when converting between formats.
 */
export interface ConversionResult {
	/** Whether conversion succeeded */
	success: boolean;
	/** Converted content (if successful) */
	content?: string;
	/** Error message (if failed) */
	error?: string;
	/** Features that couldn't be converted */
	unsupportedFeatures?: string[];
	/** Warnings about the conversion */
	warnings?: string[];
}

/**
 * Template metadata extracted during conversion.
 */
export interface TemplateMetadata {
	/** Template name */
	name: string;
	/** Template type (e.g., "article", "youtube") */
	type?: string;
	/** Source format */
	sourceFormat: "webclipper" | "templater";
	/** Detected variables */
	variables: TemplaterVariable[];
	/** Frontmatter fields */
	frontmatterFields: string[];
}
